# Лабораторная работа № 1

## Работа с библиотекой pandas

**Цель работы:** познакомиться с использованием библиотеки pandas при решении практических задач, связанных с анализом данных.

Проанализируем набор данных `Employee.csv`. Датасет содержит сведения о сотрудниках компании. Набор данных включает следующие атрибуты:

- **Education** – уровень образования (Bachelors, Masters, PHD);
- **JoiningYear** – год трудоустройства;
- **City** – город (Bangalore, Pune, New Delhi);
- **PaymentTier** – уровень оплаты (1, 2, 3);
- **Age** – возраст (лет);
- **Gender** – пол (Male, Female);
- **EverBenched** – находился ли в резерве (No/Yes);
- **ExperienceInCurrentDomain** – опыт в текущей области (лет);
- **LeaveOrNot** – уволился или нет (0 – нет, 1 – да).

## 0. Импортируем необходимые библиотеки

In [6]:
import numpy as np
import pandas as pd

## 1. Загрузите датасет из файла Employee.csv и поместите его в датафрейм

In [7]:
df = pd.read_csv('Employee.csv')

## 2.Выведем первые 6 строк данных.

In [2]:
df.head(6)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0

## 3.Выведем последние 6 строк данных.

In [3]:
df.tail(6)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

## 4.Получим общую информацию о данных (типы, количество ненулевых значений).

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), object(4)
memory usage: 327.3+ KB

## 5.Получим основные статистические характеристики числовых признаков.

In [5]:
df.describe()

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864
std,1.863377,0.561435,4.826087,1.558240,0.475047
min,2012.000000,1.000000,22.000000,0.000000,0.000000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000

## 6.Определим количество уникальных городов.

In [6]:
df['City'].nunique()

3

## 7.Выведем частоту встречаемости каждого города.

In [7]:
df['City'].value_counts()

City
Bangalore    2228
Pune         1268
New Delhi    1157
Name: count, dtype: int64

## 8.Проанализируем влияние уровня образования на увольнение.

In [8]:
df.groupby('Education')['LeaveOrNot'].mean()

Education
Bachelors    0.313524
Masters      0.487973
PHD          0.251397
Name: LeaveOrNot, dtype: float64

## 9.Создадим возрастную группу и определим, какая возрастная группа увольняется чаще.

In [9]:
df['AgeGroup'] = pd.cut(df['Age'],
                       bins=[0, 30, 45, 100],
                       labels=['<30', '30-45', '45+'])

df.groupby('AgeGroup', observed=False)['LeaveOrNot'].mean()

AgeGroup
<30      0.354154
30-45    0.320029
45+           NaN
Name: LeaveOrNot, dtype: float64

## 10.Проанализируем влияние пола на увольнение и уровень оплаты.

In [10]:
df.groupby('Gender').agg({
    'LeaveOrNot': 'mean',
    'PaymentTier': ['mean', 'median']
})

       LeaveOrNot PaymentTier
             mean        mean median
Gender
Female   0.471467    2.537600    3.0
Male     0.257739    2.806695    3.0

## 11.Оценим влияние уровня оплаты (PaymentTier) на текучесть кадров.

In [11]:
df.groupby('PaymentTier')['LeaveOrNot'].mean()

PaymentTier
1    0.366255
2    0.599129
3    0.275200
Name: LeaveOrNot, dtype: float64

## 12.Рассчитаем общий стаж (Experience) и сгруппируем по стажу, чтобы выявить зависимость между стажем и увольнением.

In [12]:
df['Experience'] = 2026 - df['JoiningYear']

df['ExpGroup'] = pd.cut(df['Experience'],
                       bins=[0, 2, 5, 40],
                       labels=['<2', '2-5', '5+'])

df.groupby('ExpGroup', observed=False)['LeaveOrNot'].mean()

ExpGroup
<2          NaN
2-5         NaN
5+     0.343864
Name: LeaveOrNot, dtype: float64

## 13.Изучим влияние нахождения на бенче (EverBenched) на увольнение и средний опыт в текущей области.

In [13]:
df.groupby('EverBenched').agg({
    'LeaveOrNot': 'mean',
    'ExperienceInCurrentDomain': 'mean'
})

             LeaveOrNot  ExperienceInCurrentDomain
EverBenched
No             0.331257                   2.904910
Yes            0.453975                   2.912134

## 14.Построим сводную таблицу: средний возраст и количество сотрудников в зависимости от опыта в текущей области и нахождения на бенче.

In [15]:
pd.pivot_table(df,
               values='Age',
               index='ExperienceInCurrentDomain',
               columns='EverBenched',
               aggfunc=['mean', 'count'])

                                mean             count
EverBenched                       No        Yes     No    Yes
ExperienceInCurrentDomain
0                          31.659375  32.628571  320.0   35.0
1                          30.958333  31.148148  504.0   54.0
2                          29.158004  29.544000  962.0  125.0
3                          28.685915  27.618421  710.0   76.0
4                          28.459364  27.865854  849.0   82.0
5                          29.391892  28.619048  814.0  105.0
6                          35.125000        NaN    8.0    NaN
7                          38.500000  34.000000    8.0    1.0

## 15.Построим сводную таблицу: вероятность увольнения в зависимости от пола и уровня образования.

In [16]:
pd.pivot_table(df,
               values='LeaveOrNot',
               index=['Gender', 'Education'],
               aggfunc='mean')

                  LeaveOrNot
Gender Education
Female Bachelors    0.486411
       Masters      0.452830
       PHD          0.260870
Male   Bachelors    0.198984
       Masters      0.513944
       PHD          0.245455

## 16.Создадим новый признак — отношение опыта в текущей области к возрасту (experience_to_age_ratio).

In [17]:
df['experience_to_age_ratio'] = df['ExperienceInCurrentDomain'] / df['Age']
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,AgeGroup,Experience,ExpGroup,experience_to_age_ratio
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,30-45,9,5+,0.000000
1,Bachelors,2013,Pune,1,28,Female,No,3,1,<30,13,5+,0.107143
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,30-45,12,5+,0.052632
3,Masters,2016,Bangalore,3,27,Male,No,5,1,<30,10,5+,0.185185
4,Masters,2017,Pune,3,24,Male,Yes,2,1,<30,9,5+,0.083333

## 17.Сохраним обогащённый датафрейм в CSV-файл для дальнейшего использования.

In [19]:
df.to_csv('result.csv', index=False)

## 18.Проведём корреляционный анализ числовых признаков.

In [20]:
df.corr(numeric_only=True)

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot,Experience,experience_to_age_ratio
JoiningYear,1.000000,-0.096078,0.013165,-0.036525,0.181705,-1.000000,-0.033659
PaymentTier,-0.096078,1.000000,0.007631,0.018314,-0.197638,0.096078,0.012768
Age,0.013165,0.007631,1.000000,-0.134643,-0.051126,-0.013165,-0.361447
ExperienceInCurrentDomain,-0.036525,0.018314,-0.134643,1.000000,-0.030504,0.036525,0.963170
LeaveOrNot,0.181705,-0.197638,-0.051126,-0.030504,1.000000,-0.181705,-0.012390
Experience,-1.000000,0.096078,-0.013165,0.036525,-0.181705,1.000000,0.033659
experience_to_age_ratio,-0.033659,0.012768,-0.361447,0.963170,-0.012390,0.033659,1.000000

## В ходе лабораторной работы был проведён анализ данных сотрудников компании с использованием библиотеки pandas. Были выявлены основные факторы, влияющие на текучесть кадров: возраст, уровень оплаты труда и стаж работы. Также было показано, что комплексный анализ нескольких факторов позволяет глубже понять причины увольнения сотрудников.